#!/bin/bash
# ==============================================================================
# MODULE: auto_gdbinit.sh
# DESCRIPTION: Dynamically generates the absolute paths for GDB debugging.
# ==============================================================================


PROJECT_ROOT=$1
BUILD_OUTPUT_DIR=$2
CROSS_COMPILE=$3
elf_path=$4
ARCH=$5
ARCH_SIZE=$6
BOARD_DIR=$7

GDB_AUTO_GDBINIT_FILE="$PROJECT_ROOT/scripts/auto_gdbinit"

SYSROOT_PATH=
SRC_PATH="$PROJECT_ROOT"


ARCH_GDB_INIT_FILE="$PROJECT_ROOT/scripts/gdb_helper/archsize${ARCH_SIZE}_${ARCH}.gdb"
ARCH_IN_NUMBER=0xFFFF


echo ">>> [INFO] Generating dynamic GDB init script..."

# 4. Write the GDB commands using a Heredoc
# Note: We escape the $ inside the heredoc (\$) so bash prints the literal
# dollar sign for GDB convenience variables, but expands the bash variables.
cat <<EOF > "$GDB_AUTO_GDBINIT_FILE"
# ==============================================================================
# AUTOGENERATED FILE - DO NOT EDIT MANUALLY
# Generated by: scripts/generate_gdbinit.sh
# ARCH: $ARCH | BOARD_DIR: $BOARD_DIR
# ==============================================================================

# 1. Define Convenience Variables
set \$BUILD_OUTPUT_DIR = "$BUILD_OUTPUT_DIR"
#set \$SYSROOT_PATH = "$SYSROOT_PATH"
set \$KERNEL_SRC_PATH = "$SRC_PATH"
set \$DEBUG_TARGET_VMLINUX = "$elf_path"


set \$TARGET_BOARD = "$TARGET_BOARD"
set \$build_ARCH = "$ARCH"
set \$build_ARCH_SIZE = "$ARCH_SIZE"
set \$build_CROSS_COMPILE = "$CROSS_COMPILE"
set \$PROJECT_ROOT="$PROJECT_ROOT"


#set sysroot $SYSROOT_PATH
directory $SRC_PATH

add-auto-load-safe-path $BUILD_OUTPUT_DIR
add-auto-load-safe-path $SRC_PATH


#printf ">>> [AUTO] GDB Sysroot set to: %s\n", \$SYSROOT_PATH
printf ">>> [AUTO] GDB Source Directory added: %s\n", \$KERNEL_SRC_PATH

show sysroot
show directories

source $ARCH_GDB_INIT_FILE
EOF

echo ">>> [SUCCESS] GDB setup written to: $GDB_AUTO_GDBINIT_FILE"